version: "3.4"

services:
  # Service命名為 init
  init:
    # 告訴 docker-compose 要先幫我執行 docker build (要事先準備Dockerfile) 的動作
    build: ./content-init
    # docker image 要命名成... 
    image: content-init
    # 告訴 docker-compose 建立的 container 名稱
    #container_name: mongo-ini    
    # 建立內部服務連結名稱（所指定的服務要先起來）
    depends_on:
      - mongo
    # 給定 container 內的 linux 環境變數名稱(此例為連線到 mongodb 的連線資訊)
    environment:
      MONGODB_CONNECTION: mongodb://mongo:27017/contentdb
