apiVersion: batch/v1
kind: Job
metadata:
  name: init
spec:
  template:
    spec:
      containers:
      - name: init
        image: localhost:5000/content-init
        env:
          - name: MONGODB_CONNECTION
            valueFrom:
              secretKeyRef:
                name: mongo
                key: db
      restartPolicy: Never
  backoffLimit: 4